name: yod_nak_ram_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  yod:
    git:
      url: https://github.com/corp-yod/yod.git
      ref: master

  yod_nak_ram_ui_kit:
    git:
      url: https://github.com/corp-yod/yod-nak-ram-ui-kit.git
      ref: develop

  yod_presentation_fake_store:
    # path: ../yod-presentation-fake-store
    git:
      url: https://github.com/corp-yod/yod-presentation-fake-store.git
      ref: main

  yod_navigator:
    git:
      url: https://github.com/corp-yod/yod-navigator.git
      ref: main

  yod_presentation_travel_to_gether:
    git:
      url: https://github.com/corp-yod/yod-presentation-travel-to-gether.git
      ref: develop

dependency_overrides:
  yod_nak_ram_ui_kit:
    path: ../yod-nak-ram-ui-kit

  yod_navigator:
    path: ../yod-navigator

  yod_presentation_travel_to_gether:
    path: ../yod-presentation-travel-to-gether

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  yod_nak_ram_ui_kit:
    # path: ../yod-nak-ram-ui-kit
    git:
      url: https://github.com/corp-yod/yod-nak-ram-ui-kit.git
      ref: master

  yod_presentation_fake_store:
    # path: ../yod-presentation-fake-store
    git:
      url: https://github.com/corp-yod/yod-presentation-fake-store.git
      ref: main

flutter:
  uses-material-design: true
